config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'posts#index'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/following/:id' => 'users#following'
  get '/followers/:id' => 'users#followers'



  get '/tops/home' => "tops#home"
  resources :relationships, only: %i(create destroy)
  resources :chat, only: %i(create show)
  resources :posts, only: %i(index new create show destroy) do
    resources :movies, only: %i(create)
    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  validates :message, presence: true, length: { maximum: 50 }
  belongs_to :chat_room
  belongs_to :user
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_messages
  has_many :chat_room_users
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true, length: { maximum: 50 }
  validates :user_id, presence: true
  validates :post_id, presence: true

  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :post

  validates :video, presence: true
  
  mount_uploader :video, VideoUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  has_many :movies, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :movies

  def liked_by(user)
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :chat_messages
  has_many :chat_room_users
  has_many :posts, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :followers, through: :follower_relationships
  has_many :likes
  has_many :comments

  mount_uploader :profile_photo, ProfilePhotoUploader
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, length: { maximum: 50 }
  
  enum gender: %i(未選択 男子 女子), _prefix: true
  enum sports_event: %i(
    未選択 アーチェリー ウエイトリフティング カヌー ゴルフ サーフィン サッカー スケートボード セーリング ソフトボール テコンドー テニス 軟式テニス トライアスロン バスケットボール バドミントン バレーボール ハンドボール フェンシング ボート ラグビー レスリング 近代五種 空手 自転車 柔道 水泳 体操 卓球 馬術 野球 軟式野球 陸上 肉体改造部
  ), _prefix: true
  enum sports_stage: %i(未選択 中学生 高校生 大学生 社会人 シニア), _prefix: true
  enum sports_level: %i(未選択 趣味 部活 アマチュア プロ), _prefix: true
  enum area: %i(未選択 北海道 青森県 岩手県 宮城県 秋田県 山形県 福島県 茨城県 栃木県 群馬県 埼玉県 千葉県 東京都 神奈川県 新潟県 富山県 石川県 福井県 山梨県 長野県 岐阜県 静岡県 愛知県 三重県 滋賀県 京都府 大阪府 兵庫県 奈良県 和歌山県 鳥取県 島根県 岡山県 広島県 山口県 徳島県 香川県 愛媛県 高知県 福岡県 佐賀県 長崎県 熊本県 大分県 宮崎県 鹿児島県 沖縄県 海外), _prefix: true

  def update_without_current_password(params, *options)
    params.delete(:current_password)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def create
    current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
    chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: params[:user_id]).map(&:chat_room).first
    if chat_room.blank?
      chat_room = ChatRoom.create
      ChatRoomUser.create(chat_room: chat_room, user_id: current_user.id)
      ChatRoomUser.create(chat_room: chat_room, user_id: params[:user_id])
    end
    redirect_to action: :show, id: chat_room.id
  end

  def show
    chat_room = ChatRoom.find_by(id: params[:id])
    if chat_room.chat_room_users.where(user_id: current_user.id).exists?
      @user = current_user
      @chat_room_user = chat_room.chat_room_users.where.not(user_id: current_user.id).first.user
      @chat_messages = ChatMessage.where(chat_room: chat_room).order(:created_at)
    else
      redirect_to root_path
      flash[:alert] = "正規のチャットルームに入室してください"
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end

  private
    def like_params
      params.permit(:post_id)
    end
end

app/controllers/posts_controller.rb
 class PostsController < ApplicationController
  #投稿した情報をログインユーザーだけに見せる
  before_action :authenticate_user!
  before_action :set_post, only: %i(show destroy)

  def new
    @post = Post.new
    @post.movies.build
  end

  def create
    @post = Post.new(post_params)
    if @post.movies.present?
      @post.save
      redirect_to root_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to root_path
      flash[:alert] = "投稿に失敗しました"
    end
  end

  def index
    @posts = Post.limit(10).includes(:movies, :user).order('created_at DESC')
  end

  def show
  end

  def destroy
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:caption, movies_attributes: [:video]).merge(user_id: current_user.id)
    end

    def set_post
      @post = Post.find_by(id: params[:id])
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def home
    render layout: false 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_photo(user)
    user.profile_photo
  end
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/chat/show.html.erb
<div id="edit-main">
  <%= render "partial/side"%>
  <div class="chat-cont">
    <div class="chatPage">
      <div class="chat-header">
        <div class="chatPartner">
          <div class="chat-partner">
            <%= image_tag default_photo(@chat_room_user).url, class: "post-profile-icon" %>
          </div>
          <div class="chat-onother-name white">
            <%= @chat_room_user.name %>
          </div>
        </div>
      </div>
      <div class="chat-background">
      <div class="container">
        <div class="messagesArea messages">
          <%= render @chat_messages %>
        </div>
        <form class="messageInputForm">
          <div　class="chat-fom">
          　<input type="text" data-behavior="room_speaker" class="messageInputForm_input" placeholder="メッセージを入力...">
          </div>
        </form>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/tops/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  </head>
  <body>
    <header class="top-header">
        <div class="top-main-logo-link">
          <%= link_to("UNIVERSE", tops_home_path, class: "top-logo-link")%>
        </div>
        <ul class="top-header-menus">
          <li>
            <%= link_to "アプリについて" ,"#", class: "top-header-menus-li" %>
          </li>
          <li>
          <%= link_to "新規登録", new_user_registration_path, class: "top-header-menus-li" %>
          </li>
          <li>
          <%= link_to "ログイン", new_user_session_path, class: "top-header-menus-li" %>
          </li>
        </ul>   
    </header>
    <div class="top-main">
      <div class="top-message">
        <h1>Take your mark?</h1>
        <p>ライバルを見つけて、あなたを強くするスポーツコミュニティアプリ</p>    
        <%= link_to("新規登録", new_user_registration_path, class: "top-signup ") %>
        <div class="a-loginform">
          <%= link_to("アカウントをお持ちの方" ,new_user_session_path , class: "top-login")%>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tops/test.html.erb
<% provide(:title, 'Sign up') %>
<div class="b-img">
  <h1 class="new-name">アカウント登録</h1>
  <div class="row">
    <div class="new-form">
      <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class:"mt-5" }) do |f| %>
        <%= devise_error_messages! %>
        <%= f.label :name, "アカウント名", class: 'new-box' %>
        <%= f.text_field :name, class: 'form-control', placeholder: "アカウント名を入力" %>
        <%= f.label :email, "メールアドレス", class: 'new-form-li'%>
        <%= f.email_field :email, class: 'form-control', placeholder: "E-mailを入力" ,autocomplete: "email"%>
        <%= f.label :password, "パスワード", class: 'new-form-li'%>
        <div class="edit-errore">
          <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %>文字以上入力してください)</em>
          <% end %><br/>
        </div>
        <%= f.password_field :password, class: 'form-control' ,placeholder:"パスワードを入力", autocomplete: "off"%>
        <%= f.label :password_confirmation, "パスワードを確認", class: 'new-form-li'%>
        <%= f.password_field :password_confirmation, class: 'form-control',placeholder: "パスワードを再確認", autocomplete: "off" %>
        <%= f.submit "登録する", class: "new-sub" %>
      <% end %>
    </div>
  </div>
</div>