config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'posts#index'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/following/:id' => 'users#following'
  get '/followers/:id' => 'users#followers'



  get '/tops/home' => "tops#home"
  resources :relationships, only: %i(create destroy)
  resources :chat, only: %i(create show)
  resources :posts, only: %i(index new create show destroy) do
    resources :movies, only: %i(create)
    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  validates :message, presence: true, length: { maximum: 50 }
  belongs_to :chat_room
  belongs_to :user
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_messages
  has_many :chat_room_users
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true, length: { maximum: 50 }
  validates :user_id, presence: true
  validates :post_id, presence: true

  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :post

  validates :video, presence: true
  
  mount_uploader :video, VideoUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  has_many :movies, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :movies

  def liked_by(user)
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :chat_messages
  has_many :chat_room_users
  has_many :posts, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :followers, through: :follower_relationships
  has_many :likes
  has_many :comments

  mount_uploader :profile_photo, ProfilePhotoUploader
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, length: { maximum: 50 }
  
  enum gender: %i(未選択 男子 女子), _prefix: true
  enum sports_event: %i(
    未選択 アーチェリー ウエイトリフティング カヌー ゴルフ サーフィン サッカー スケートボード セーリング ソフトボール テコンドー テニス 軟式テニス トライアスロン バスケットボール バドミントン バレーボール ハンドボール フェンシング ボート ラグビー レスリング 近代五種 空手 自転車 柔道 水泳 体操 卓球 馬術 野球 軟式野球 陸上 肉体改造部
  ), _prefix: true
  enum sports_stage: %i(未選択 中学生 高校生 大学生 社会人 シニア), _prefix: true
  enum sports_level: %i(未選択 趣味 部活 アマチュア プロ), _prefix: true
  enum area: %i(未選択 北海道 青森県 岩手県 宮城県 秋田県 山形県 福島県 茨城県 栃木県 群馬県 埼玉県 千葉県 東京都 神奈川県 新潟県 富山県 石川県 福井県 山梨県 長野県 岐阜県 静岡県 愛知県 三重県 滋賀県 京都府 大阪府 兵庫県 奈良県 和歌山県 鳥取県 島根県 岡山県 広島県 山口県 徳島県 香川県 愛媛県 高知県 福岡県 佐賀県 長崎県 熊本県 大分県 宮崎県 鹿児島県 沖縄県 海外), _prefix: true

  def update_without_current_password(params, *options)
    params.delete(:current_password)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def create
    current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
    chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: params[:user_id]).map(&:chat_room).first
    if chat_room.blank?
      chat_room = ChatRoom.create
      ChatRoomUser.create(chat_room: chat_room, user_id: current_user.id)
      ChatRoomUser.create(chat_room: chat_room, user_id: params[:user_id])
    end
    redirect_to action: :show, id: chat_room.id
  end

  def show
    chat_room = ChatRoom.find_by(id: params[:id])
    if chat_room.chat_room_users.where(user_id: current_user.id).exists?
      @user = current_user
      @chat_room_user = chat_room.chat_room_users.where.not(user_id: current_user.id).first.user
      @chat_messages = ChatMessage.where(chat_room: chat_room).order(:created_at)
    else
      redirect_to root_path
      flash[:alert] = "正規のチャットルームに入室してください"
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end

  private
    def like_params
      params.permit(:post_id)
    end
end

app/controllers/posts_controller.rb
 class PostsController < ApplicationController
  #投稿した情報をログインユーザーだけに見せる
  before_action :authenticate_user!
  before_action :set_post, only: %i(show destroy)

  def new
    @post = Post.new
    @post.movies.build
  end

  def create
    @post = Post.new(post_params)
    if @post.movies.present?
      @post.save
      redirect_to root_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to root_path
      flash[:alert] = "投稿に失敗しました"
    end
  end

  def index
    @posts = Post.limit(10).includes(:movies, :user).order('created_at DESC')
  end

  def show
  end

  def destroy
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:caption, movies_attributes: [:video]).merge(user_id: current_user.id)
    end

    def set_post
      @post = Post.find_by(id: params[:id])
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def home
    render layout: false 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_photo(user)
    user.profile_photo
  end
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/likes/create.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "いいね", post_like_path(@post.id, @like), method: :DELETE, remote: true, class: "loved hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/like_text", { likes: @post.likes } %>');

app/views/likes/destroy.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "いいねを取り消す", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/like_text", { likes: @post.likes } %>');

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2 ">
    <% if comment.user == current_user %>
      <%= link_to "", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong class="posts-hover">
        <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>：
      </strong>
    </span>
    <span>
      <%= comment.comment %>
    </span>
  </div>
<% end %>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>と<strong>
      <%= + like.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "と" + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.name %>
    <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/posts/index.html.erb
<div id="edit-main">
  <%= render "partial/side"%>
  <div class="posts-index-cont">
    <% @posts.each do |post| %>
      <div class="posts-index-card-box">
        <div class="posts-index-all-card">
          <div class="card-header d-flex" id="card-header-sub">
            <%= link_to user_path(post.user), class: "no-text-decoration" do %>
              <%= image_tag default_photo(post.user).url, class: "post-profile-icon" %>
            <% end %>
            <%= link_to user_path(post.user), class: "no-text-decoration user-name posts-hover",title: post.user.name do %>
              <strong><%= post.user.name %></strong>
            <% end %>
            <div class="white no-text-decoration user-name posts-caption">
              <%= post.caption %>
            </div> 
            <% if post.user_id == current_user.id %>
              <%= link_to post_path(post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                <div class="delete-post-icon">
                </div>
              <% end %>
            <% end %>
          </div>
          <div class="card-body card-body-color">
            <%= link_to(post_path(post)) do %>
              <%= video_tag post.movies.first.video, :size => "500x500", class: "card-img-top" %>
            <% end %>
          </div>
          <div class="card-body" id="card-body-color">
            <div id="like-icon-post-<%= post.id.to_s %>">
              <% if post.liked_by(current_user).present? %>
                <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
              <% else %>
                <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
              <% end %>
            </div>
            <div class="like white" id="like-text-post-<%= post.id.to_s %>">
              <%= render "like_text", { likes: post.likes } %>
            </div>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),class: "light-color post-time no-text-decoration" %>
            <hr>
            <div class="card-right-comment">
              <div class="comment-post-id">
                <div class="m-2">
                  <div class="white" id="comment-post-<%= post.id.to_s %>">
                    <%= render 'comment_list', post: post %>
                  </div>
                </div>
              </div>
            </div>
            <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
              <%= form_with model: [post, Comment.new], class: "w-100" do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :post_id, value: post.id %>
                <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div id="edit-main">
  <%= render "partial/side"%>
  <div class="edit-cont">
    <div class="postsnew-card">
      <div class="new-box white">
        <%= form_with model: @post do |f| %>
          <%= image_tag default_photo(current_user).url, class: "post-profile-icon new-user-image" %>
          <div class="postsnew-form">
            <%= f.text_field :caption, class: "form-control ", placeholder: "タイトル" %>
          </div>
          <%= f.fields_for :movies do |m| %>
            <%= m.file_field :video %>
          <% end %>
          <div class="postsnew-btn">
            <%= f.submit "投稿する", class: "btn postsnew-btn-btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div id="edit-main">
  <%= render "partial/side"%>
  <div class="edit-cont">
    <div class="card-header  d-flex" id="card-header-show-sub">
      <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
        <%= image_tag default_photo(@post.user).url, class: "post-profile-icon" %>
      <% end %>
      <%= link_to user_path(@post.user), class: "no-text-decoration user-name posts-hover", title: @post.user.name do %>
        <strong><%= @post.user.name %></strong>
      <% end %>
      <% if @post.user_id == current_user.id %>
        <%= link_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
          <div class="delete-post-icon"> </div>
        <% end %>
      <% end %>
    </div>
    <div class="posts-show-card">
      <div class="posts-show-title white">
        <%= @post.caption %>
      </div> 
      <iframe width="950" height="550" src="<%= @post.movies.first.video %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <div class="posts-show-comment-box">
      <div class="row actions posts-show-comment" id="comment-form-post-<%= @post.id.to_s %>">
        <%= form_with model: [@post, Comment.new],  class: "w-100" do |f| %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :post_id, value: @post.id %>
          <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
        <% end %>
      </div>
      <div class="card-right-comment">
        <div class="comment-post-id white">
          <div class="m-2">
            <div id="comment-post-<%= @post.id.to_s %>">
                <%= render 'comment_list', post: @post %>
            </div>
          </div>
        </div>
      </div>
      <div class="row parts">
        <div id="like-icon-post-<%= @post.id.to_s %>">
          <% if @post.liked_by(current_user).present? %>
            <%= link_to "いいねを取り消す", post_like_path(@post.id, @post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
          <% else %>
            <%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>
          <% end %>
        </div>
      </div>
      <div class="white" id="like-text-post-<%= @post.id.to_s %>">
        <%= render "like_text", { likes: @post.likes } %>
      </div>
      <div class="post-time">
        <%= time_ago_in_words(@post.created_at).upcase %>前 
      </div>
      <hr>
    </div>
  </div>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div>
    <%= f.hidden_field :following_id %>
  </div>
  <%= f.submit "フォロー", class: "follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow-btn ">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>  

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats show-stat">
  <% if @user == current_user %>
  <a href="<%= "/following/#{@user.id}"%>">
  <%end%>フォロー 
  <strong id="following" class="stat">
    <%= @user.followings.count %>
  </strong>
  </a>
  <% if @user == current_user %>
  <a href="<%= "/followers/#{@user.id}" %>">
  <%end%>フォロワー 
  <strong id="followers" class="stat">
    <%= @user.followers.count %>
  </strong>
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー解除", class: "follow-btn" %>
<% end %>

app/views/users/show.html.erb
<div id="edit-main">
  <%= render "partial/side"%>
  <div class="edit-cont">
    <div class="white">
      <div class="show-user-image">
        <%= image_tag default_photo(@user).url, class: "side-user-image " %>
      </div>
      <div class="show-username ">
        <h3>
          <%= @user.name %>
        </h3>
      </div>
      <% if @user == current_user %>
        <div class="show-username">
          <p>
            <%= @user.email %>
          </p>
        </div>
      <% end %>
      <div class="show-stat">
        <%= render 'stats' %>
        <%= render 'follow_form' %>
      </div>
      <% if @user == current_user %>
      <div class="show-prof">
        <%= link_to "プロフィールを編集", edit_user_registration_path, class: "show-btn" %>
        <button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"></button>
      </div>
      <% end %>
      <div class="show-mini-box">
        <div class="show-box-sub">
          <div>
            自己紹介
          </div>
          <%= @user.self_introduction %>
        </div>
        <div class="show-box-sub"> 性別：
          <%= @user.gender %>
        </div>
        <div class="show-box-sub"> 地域：
          <%= @user.area %>
        </div>
        <div class="show-box-sub"> 専門競技：
          <%= @user.sports_event %>
        </div>
        <div class="show-box-sub"> 競技ステージ：
          <%= @user.sports_stage %>
        </div>
        <div class="show-box-sub"> 競技レベル：
          <%= @user.sports_level %>
        </div>
      </div>
      <% if @user == current_user %>
        <div class="show-signout">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "show-signout-li" %>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/users/show_follow.erb
<div id="edit-main">
  <%= render "partial/side"%>
  <% if @users == nil%>
    <div class="follow-nil-cont">
      <div class="follow-nil-copy white">
        フォローがありません。
      </div>
    </div>
  <% else %>
    <div class="edit-cont">
      <div class="follow-page white">
        <h4>フォロー一覧</h4>
      </div>
      <% @users.each do |user| %>
        <div class="follow-box white">
          <div class="follow-subsub-box">
            <div class="follow-image">
              <%= image_tag default_photo(user).url, class: "post-profile-icon" %>
            </div>
            <div class="follow-subbox">
              <div class="followname">
                <%= link_to user_path(user), class: "no-text-decoration posts-hover" do %>
                  <%= user.name %>
                <%end%>
              </div>
              <div class="follow-link">
                <%= link_to '詳細', user_path(user),class: "follow-link-li" %>
              </div>
              <div class="follow-chat-box">
                <%= form_tag :chat_index, method: :post do %>
                  <input name="user_id" type="hidden" value="<%= user.id %>" />
                  <%= submit_tag 'メッセージ', class: "follow-chat" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show_follow.html.erb
<div id="edit-main">
  <%= render "partial/side"%>
  <% if @users == nil%>
    <div class="follow-nil-cont">
      <div class="follow-nil-copy white">
        フォローがありません。
      </div>
    </div>
  <% else %>
    <div class="edit-cont">
      <% @users.each do |user| %>
        <div class="follow-box white">
          <div class="follow-subsub-box">
            <div class="follow-image">
              <%= image_tag default_photo(user).url, class: "post-profile-icon" %>
            </div>
            <div class="follow-subbox">
              <div class="followname">
                <%= link_to user_path(user), class: "no-text-decoration posts-hover" do %>
                  <%= user.name %>
                <%end%>
              </div>
              <div class="follow-link">
                <%= link_to '詳細', user_path(user),class: "follow-link-li" %>
              </div>
              <div class="follow-chat-box">
                <%= form_tag :chat_index, method: :post do %>
                  <input name="user_id" type="hidden" value="<%= user.id %>" />
                  <%= submit_tag 'メッセージ', class: "follow-chat" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show_follower.html.erb
<div id="edit-main">
  <%= render "partial/side"%>
  <div class="edit-cont">
    <div class="follow-page white">
      <h4>フォロワー一覧</h4>
    </div>
    <% @users.each do |user| %>
      <div class="follow-box white">
        <div class="follow-subsub-box">
          <div class="follow-image">
            <%= image_tag default_photo(user).url, class: "post-profile-icon" %>
          </div>
          <div class="follow-subbox">
            <div class="followname">
              <%= user.name %>
            </div>
            <div class="follow-link">
              <%= link_to '詳細', user_path(user),class: "follow-link-li" %>
            </div>
            <div class="follow-chat-box">
              <%= form_tag :chat_index, method: :post do %>
                <input name="user_id" type="hidden" value="<%= user.id %>" />
                <%= submit_tag 'メッセージ', class: "follow-chat" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>